### ISSUE TITLE
Módulo diárias - Geração de relatório de diárias de empenhos

### ISSUE THREAD

**Issue by ViniciusR** [GestUAB/GestUAB#13]
Após a aprovação de uma solicitação de diária, feita no módulo financeiro, uma nova linha deve ser adicionada ao relatório de diárias. 

Cada linha deve conter os seguintes dados:
- Número do empenho;
- Número do convênio utilizado;
- Nome do beneficiário; 
- Data do empenho;
- Datas da diária;
- Texto "referente";
- Valor;
- Valor total;
- Conta para o depósito;
- Quantidade de diárias;
- Data do pagamento.

O relatório é gerado automaticamente, não deve possuir nenhuma interação de entrada com o usuário.  
Os dados de cada linha do relatório são os mesmo inseridos pelo usuário no módulo financeiro ao solicitar uma nova diária.

**Comment by thild** [comment]
See #11
