### ISSUE TITLE
Teste do módulo de Controle de viagens

### ISSUE THREAD

**Issue by kustervieira** [GestUAB/GestUAB#17]
Neste módulo o teste será  acessar a página para controle de viagens e preenche as informações. Depois de preenchidas todas as informações  verificar os possiveis erros antes do usuário poder salvar e imprimi-lo.

Campos a serem verificados:
Selecionar o Curso (Se todos os cursos estão incluidos e se estão sendo cadastrados corretamentos)
Numero do memorando (verifica se nao tem memorando com o mesmo numero)
Data da viagem (saída e retorno) (Verificar as peculiaridades com relação a data da viagem )
Horário de saída (verificar se nao bate horios das viagens)
Veículo (Carro da Unicentro, Táxi) (Carros disponiveis e carros cadastrados)
Motorista (Lista dos motoristas disponíveis para selecionar um)
Destino (verificar se o destino é 'valido' )
Sistema/Pagamento (Ok se estiver paga a diária)

**Comment by kustervieira** [comment]
Caso haja mais restrições a serem verificadas peço a colaboração dos colegas para identifica-las.

**Comment by thild** [comment]
Duplicated: https://github.com/thild/GestUAB/issues/10
