### ISSUE TITLE
Tutorial/Padronização no uso do git

### ISSUE THREAD

**Issue by AndreZago** [GestUAB/GestUAB#29]
Elaborar um tutorial de Git + GitHub, visto que muitas pessoas não tem conhecimento no uso do git, isso serve também para padronizar o uso dele.

**Comment by fabiosammy** [comment]
Pronto!
https://github.com/thild/GestUAB/wiki/Utilizando-o-Git

Caso ainda haja dúvidas, favor comentar, caso contrário, "closed to issue".

**Comment by AndreZago** [comment]
É isso ai
