### ISSUE TITLE
Requirements Survey (0.5)

### ISSUE THREAD

**Issue by fabiosammy** [GestUAB/GestUAB#45]
Do the requirements survey of libraries, services, and programs needed to run the system,  along with their versions. Ex.:
Mono >= 2.10.8 
RavenDB = Build-701
Nginx > 1.0.101
Monodevelop >= 3.4
### flpandre:
- jQuery 1.7.2 or higher - http://jquery.com/
### juliofabiane:
- Twitter Bootstrap v2.04 or higher - http://twitter.github.com/bootstrap/

**Comment by flpandre** [comment]
jQuery 1.7.2 or higher - http://jquery.com/

**Comment by juliofabiane** [comment]
Twitter Bootstrap v2.04 - http://twitter.github.com/bootstrap/

**Comment by fabiosammy** [comment]
Julio, a versão é "only"(Exatamente essa versão) "or higher"(Ou uma nova versão) ou "or higher ever"(Manter atualizado)?

**Comment by juliofabiane** [comment]
or higher

**Comment by fabiosammy** [comment]
No need more. Issue closed.
