### ISSUE TITLE
Módulo Cadastrar Viagem

### ISSUE THREAD

**Issue by abariviera** [GestUAB/GestUAB#7]
O professor acessa a página para cadastro de viagem e cadastra a viagem, se o cadastro estiver dentro do prazo de 15 dias de antecedência, o sistema retorna uma mensagem de confirmação que o cadastro da viagem foi efetuado, se não o sistema retorna uma mensagem avisando que não será possível cadastrar a viagem.

Campos do cadastro:
Nome do Professor
Data da Ida
Data Retorno
Horário Saída
Destino
Veículo (Carro da Unicentro, Taxi)
[ ] Opção não necessita motorista
Motivo da viagem

**Comment by arosa** [comment]
I'm on it.

**Comment by thild** [comment]
Duplicated: https://github.com/thild/GestUAB/issues/10
