### ISSUE TITLE
Review code with Nessus - 1.0 (per vulnerability)

### ISSUE THREAD

**Issue by hauptmann** [GestUAB/GestUAB#9]
Nessus is a scanning program failures / security vulnerabilities.
Search for vulnerabilities and fix the most important as they arise.

http://www.tenable.com/products/nessus

The company itself offers several tutorials on YouTube (http://www.youtube.com/user/tenablesecurity)

**Comment by loanpmotyl** [comment]
Isso ficaria a cargo da equipe de testes ?

**Comment by hauptmann** [comment]
Acredito que sim... detectar as vulnerabilidades seria a principal atividade da equipe de testes. Agora, para corrigir elas todos poderiam ajudar. (Minha opinião :)

**Comment by loanpmotyl** [comment]
Ok .. deixa com agente então :D

**Comment by kustervieira** [comment]
OK.

**Comment by hauptmann** [comment]
Para instalação no Ubuntu 12.04: 
http://hackertarget.com/nessus-5-on-ubuntu-12-04-install-and-mini-review/

# dpkg -i Nessus-5.0.1-ubuntu1110_amd64.deb

# /etc/init.d/nessusd start

Depois de instalado, configure na 
localhost:8834

**Comment by thild** [comment]
Moved to Trello.
